"""db tables setup

Revision ID: 3e32fe6a83b2
Revises: 
Create Date: 2025-02-27 00:20:11.119531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e32fe6a83b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('investments',
    sa.Column('investment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('scheme_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheme_code', sa.Integer(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('fund_family', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('investment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investments')
    op.drop_table('users')
    # ### end Alembic commands ###
